# Generated by Django 4.2.1 on 2023-06-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='USER1589872023', editable=False, max_length=20, unique=True),
        ),
    ]
