# Generated by Django 4.2.1 on 2023-06-09 08:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='USER3592532023', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/images/', location='D:/Testing Project/Svelte/Svelte_Web/Svelte_Web/static/images'), upload_to='user-images'),
        ),
    ]
