# Generated by Django 4.2.1 on 2023-06-07 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(default=uuid.UUID('e12e9b19-6512-43d3-abb3-4915caa4e633'), editable=False, primary_key=True, serialize=False),
        ),
    ]
