# Generated by Django 4.2.1 on 2023-06-07 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(default=uuid.UUID('a2b9288e-6a70-4ef0-85fc-a8366d3994bb'), editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
