# Generated by Django 4.2.1 on 2023-06-07 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_cart_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b23eaa67-b362-422b-9085-1281c3ee18fd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
