# Generated by Django 4.2.1 on 2023-06-07 19:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3779bb6-eccc-4af6-a749-18d1276923ae'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
