# Generated by Django 4.2.1 on 2023-06-09 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b570649-2bc8-43c5-990d-c91f83a19e50'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
